/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.0
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class vision_data_t implements lcm.lcm.LCMEncodable
{
    public double distance;

    public double direction_delta;

 
    public vision_data_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8ae909315bd158beL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.vision_data_t.class))
            return 0L;
 
        classes.add(lcmtypes.vision_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.distance); 
 
        outs.writeDouble(this.direction_delta); 
 
    }
 
    public vision_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public vision_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.vision_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.vision_data_t o = new lcmtypes.vision_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.distance = ins.readDouble();
 
        this.direction_delta = ins.readDouble();
 
    }
 
    public lcmtypes.vision_data_t copy()
    {
        lcmtypes.vision_data_t outobj = new lcmtypes.vision_data_t();
        outobj.distance = this.distance;
 
        outobj.direction_delta = this.direction_delta;
 
        return outobj;
    }
 
}

