# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters

# for RL Locomotion by KK-Zhou
init_pos    : [0, -0.76, 1.48]
body_height : 0.34
actionScale : 0.25
rlKp          : [20, 20, 20]
rlKd          : [0.5, 0.5, 0.5]
policy_dt   : 0.01 # 100Hz
emergency_orientation: 50.0 # pitch over 50 degrees will be considered as emergency
logData : -1 # 1: log data, -1: not log data
policyDirNum : 1 # log directory number
