"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class vision_data_t(object):

    __slots__ = ["distance", "direction_delta"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.distance = 0.0
        """ LCM Type: double """
        self.direction_delta = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(vision_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.distance, self.direction_delta))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vision_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vision_data_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = vision_data_t()
        self.distance, self.direction_delta = struct.unpack(">dd", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if vision_data_t in parents: return 0
        tmphash = (0x8ae909315bd158be) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if vision_data_t._packed_fingerprint is None:
            vision_data_t._packed_fingerprint = struct.pack(">Q", vision_data_t._get_hash_recursive([]))
        return vision_data_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vision_data_t._get_packed_fingerprint())[0]

